/*
 * @Author: atdow
 * @Date: 2022-01-29 23:52:21
 * @LastEditors: null
 * @LastEditTime: 2022-01-30 19:55:23
 * @Description: file description
 */
// 符号-->图片路径
export const EMOTIONS_DATA = {
    '/{Angel}': require("./emotions/Angel.png"),
    '/{Angry1}': require("./emotions/Angry1.png"),
    '/{Angry2}': require("./emotions/Angry2.png"),
    '/{Blushing1}': require("./emotions/Blushing1.png"),
    '/{Blushing2}': require("./emotions/Blushing2.png"),
    '/{Crying}': require("./emotions/Crying.png"),
    '/{Dead}': require("./emotions/Dead.png"),
    '/{Delightful}': require("./emotions/Delightful.png"),
    '/{Disappointed1}': require("./emotions/Disappointed1.png"),
    '/{Disappointed}': require("./emotions/Disappointed.png"),
    '/{Doh}': require("./emotions/Doh.png"),
    '/{DollarEyes}': require("./emotions/DollarEyes.png"),
    '/{EyesOpen}': require("./emotions/EyesOpen.png"),
    '/{EyesUp}': require("./emotions/EyesUp.png"),
    '/{Frown1}': require("./emotions/Frown1.png"),
    '/{Frown2}': require("./emotions/Frown2.png"),
    '/{Geek}': require("./emotions/Geek.png"),
    '/{Grin1}': require("./emotions/Grin1.png"),
    '/{Grin2}': require("./emotions/Grin2.png"),
    '/{Grin3}': require("./emotions/Grin3.png"),
    '/{Grin4}': require("./emotions/Grin4.png"),
    '/{Grin5}': require("./emotions/Grin5.png"),
    '/{GrinDrop}': require("./emotions/GrinDrop.png"),
    '/{Headache1}': require("./emotions/Headache1.png"),
    '/{Headache2}': require("./emotions/Headache2.png"),
    '/{HeartEyes}': require("./emotions/HeartEyes.png"),
    '/{Hrumph}': require("./emotions/Hrumph.png"),
    '/{Ill}': require("./emotions/Ill.png"),
    '/{JazzHands}': require("./emotions/JazzHands.png"),
    '/{KissBlushing}': require("./emotions/KissBlushing.png"),
    '/{KissHappyEyes}': require("./emotions/KissHappyEyes.png"),
    '/{KissHeart}': require("./emotions/KissHeart.png"),
    '/{Kiss}': require("./emotions/Kiss.png"),
    '/{LaughingTears}': require("./emotions/LaughingTears.png"),
    '/{NervousSmile}': require("./emotions/NervousSmile.png"),
    '/{Notimpressed}': require("./emotions/Notimpressed.png"),
    '/{Nurse}': require("./emotions/Nurse.png"),
    '/{Pondering}': require("./emotions/Pondering.png"),
    '/{Sad1}': require("./emotions/Sad1.png"),
    '/{Sad2}': require("./emotions/Sad2.png"),
    '/{Sad3}': require("./emotions/Sad3.png"),
    '/{SadWithFrown}': require("./emotions/SadWithFrown.png"),
    '/{Sigh}': require("./emotions/Sigh.png"),
    '/{Sigh2}': require("./emotions/Sigh2.png"),
    '/{SmileUpsidedown}': require("./emotions/SmileUpsidedown.png"),
    '/{Smile}': require("./emotions/Smile.png"),
    '/{Smirk}': require("./emotions/Smirk.png"),
    '/{Spooky}': require("./emotions/Spooky.png"),
    '/{Sunglasses}': require("./emotions/Sunglasses.png"),
    '/{SurprisedRaisedBrows}': require("./emotions/SurprisedRaisedBrows.png"),
    '/{SurprisedSadRaisedBrows}': require("./emotions/SurprisedSadRaisedBrows.png"),
    '/{SurprisedSad}': require("./emotions/SurprisedSad.png"),
    '/{Surprised}': require("./emotions/Surprised.png"),
    '/{Tear1}': require("./emotions/Tear1.png"),
    '/{Tear2}': require("./emotions/Tear2.png"),
    '/{TiredDrop}': require("./emotions/TiredDrop.png"),
    '/{TongueOut1}': require("./emotions/TongueOut1.png"),
    '/{TongueOut2}': require("./emotions/TongueOut2.png"),
    '/{TongueOut3}': require("./emotions/TongueOut3.png"),
    '/{TongueOut4}': require("./emotions/TongueOut4.png"),
    '/{Wink}': require("./emotions/Wink.png"),
    '/{WipingTear}': require("./emotions/WipingTear.png"),
    '/{Wounded}': require("./emotions/Wounded.png"),
    '/{Yelling}': require("./emotions/Yelling.png"),
    '/{Zipped}': require("./emotions/Zipped.png"),
    '/{Zzz}': require("./emotions/Zzz.png"),
}

// 符号-->中文
export const EMOTIONS_ZHCN = {
    '/{Angry 1}': '[生气1]',
    '/{Angry 2}': '[生气2]',
    '/{Angry 1}': '[Delightful]',
}
// [{key:"/{Angry 1}",value:require("./emotions/Angry 1.png")}]
export const EMOTIONS_ARR = Object.keys(EMOTIONS_DATA).map(key => ({ key: key, value: EMOTIONS_DATA[key] }))